name: Publish to GH Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: find latest version of janet
        uses: oprypin/find-latest-tag@v1
        with:
          repository: janet-lang/janet
          releases_only: true
          prefix: 'v'
        id: janet-ver
      - name: download janet
        run: curl -LO https://github.com/janet-lang/janet/releases/download/${{ steps.janet-ver.outputs.tag }}/janet-${{ steps.janet-ver.outputs.tag }}-linux.tar.gz
      - name: extract janet
        run: tar -xvzf janet-${{ steps.janet-ver.outputs.tag }}-linux.tar.gz
      - name: add directory to path
        run: echo "::add-path::janet-${{ steps.janet-ver.outputs.tag }}-linux"
      - name: make modules directory
        run: mkdir modules
      - name: set JANET_PATH
        run: echo "::set-env name=JANET_PATH::modules"
      - name: set JANET_LIBPATH
        run: echo "::set-env name=JANET_LIBPATH::janet-${{ steps.janet-ver.outputs.tag }}-linux"
      - name: set JANET_HEADERPATH
        run: echo "::set-env name=JANET_HEADERPATH::janet-${{ steps.janet-ver.outputs.tag }}-linux"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Clone norgolith
        run: |
          git clone https://github.com/boltlessengineer/norgolith
          cd norgolith
          git checkout norg-dialect

      - name: Install norgolith
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path norgolith

      - name: Use it
        run: lith build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
